### ISSUE TITLE
json file

### ISSUE THREAD

**Issue by SISTMrL** [fredzzhang/spatio-attentive-graphs#18]
hello, this is my first work on hoi, and can you explain the meaning of instances_train2015.json, instances_val2015.json, coco80tohico80.json, coco91tohico80.json, what they are represented?

**Comment by fredzzhang** [comment]
Hi, @SISTMrL 

`instances_train2015.json` and `instances_test2015.json` are the reformatted annotation files. They essentially contain identical content as the annotations stored in `.mat` files. `coco80tohico80.json` and `coco91tohico80.json` contain the object index correspondence between the COCO classes and HICO-DET classes.

Let me know if you have other questions.

Cheers,
Fred
