### ISSUE TITLE
About mAP in your paper

### ISSUE THREAD

**Issue by dreamPoet** [fredzzhang/spatio-attentive-graphs#25]
Hi, I found that in your paper, there is a mAP 27.18 model on HICO-DET. I wonder how this model is trained as I did not find corresponding one in this repo.

**Comment by fredzzhang** [comment]
Hi, @dreamPoet 

Thanks for taking interest in our paper.

The model with `27.18` mAP is precisely the same model we provided in the repo. The difference is a few hyper-parameters. In the paper, we used `0.5` as the threshold for object detection scores, which we later found to be not optimal. Instead, in this repo, the threshold has been changed to `0.2`. That gives `28.54` mAP for the same model.

Hope that answers your questions.

Cheers,
Fred

**Comment by fredzzhang** [comment]
As there haven't been any follow-ups, I assume there are no further questions. Closing the issue now.
