### ISSUE TITLE
About mAP in your paper

### ISSUE THREAD

**Issue by hutao568** [fredzzhang/spatio-attentive-graphs#29]
The highest precision in this repo is pointing to DRG, but your issue says that your highest precision is 28.54
![image](https://user-images.githubusercontent.com/17766186/104881986-3c386b00-599d-11eb-8cf3-74bb1ed9102d.png)
![image](https://user-images.githubusercontent.com/17766186/104882061-583c0c80-599d-11eb-904f-7f56ae94f378.png)

**Comment by fredzzhang** [comment]
Hi, @hutao568 

All of the numbers in the table are the results of our model, which is provided in the repo. If you read it carefully, the first column lists different sources of detectors. In particular, `28.54` mAP is achieved using the object detections provided by the DRG repo, but with our HOI model.

Let me know if you have other questions.

Cheers,
Fred

**Comment by fredzzhang** [comment]
I have updated the links in commit 0b311cb77ce8a983cc8a5fa62a8412f9a3e97337, so that they will now lead to the detections other than the repos. This should clear up the confusion.

**Comment by hutao568** [comment]
Okay thank you. let me try

**Comment by fredzzhang** [comment]
Alright. I assume that has answered your questions. I'll close this now.

**Comment by hutao568** [comment]
Thank you, I used the data and code you provided to reproduce your results. In addition, the highest accuracy of my reproduced results is as follows

**Comment by hutao568** [comment]
Thank you, I used the data and code you provided to reproduce your results. In addition, the highest accuracy of my reproduced results is as follows
![image](https://user-images.githubusercontent.com/17766186/105002780-c6033980-5a6c-11eb-8158-dc3900cb92f0.png)

**Comment by fredzzhang** [comment]
Good to know you are able to reproduce the results!
