### ISSUE TITLE
multi-GPU finetune fatser rcnn

### ISSUE THREAD

**Issue by hutao568** [fredzzhang/spatio-attentive-graphs#32]
When I use your detector finetune script in a multi-GPU situation, the following problems will occur. Do you have any good solutions to this problem?

RuntimeError: expected device cuda:1 and dtype Float but got device cuda:0 and dtype Float

**Comment by fredzzhang** [comment]
Hi, @hutao568 

The fine-tuning script was written to only support single-gpu training. Unfortunately, I'm currently occupied with a new project, so I don't have time to implement relevant utilities now. If you want to train with multiple gpus, you'll have to read the script and make corresponding modifications.

Cheers,
Fred

**Comment by hutao568** [comment]
Okay thank you
