### ISSUE TITLE
About label generate

### ISSUE THREAD

**Issue by hutao568** [fredzzhang/spatio-attentive-graphs#50]
Hello, I am a bit confused about the calculation of the classification loss in your code. If you have time, can you give me an answer?
https://github.com/fredzzhang/spatio-attentive-graphs/blob/main/interaction_head.py#L182
In your postprocess function, you pass in the one-hot form of the prediction result of each pair and the one-hot form of the label. Next, you use a series of magic operations to convert the one-hot form of the label into one I don't quite understand things.

**Comment by fredzzhang** [comment]
See #49
