### ISSUE TITLE
pretrained  model

### ISSUE THREAD

**Issue by WXLL579** [fredzzhang/spatio-attentive-graphs#79]
Hello, thx for your excellent work! Could you please give a link to the model fine-tuined on hico as shown in table 2 to get thre result of 31.33 24.72 33.31 ? 
![Uploading image.png…]()

**Comment by WXLL579** [comment]
PPDM [18] Hourglass-104 21.73 13.78 24.10
Bansal et al. [2] ResNet-101 21.96 16.43 23.63
VCL [14] ResNet50 23.63 17.21 25.55
DRG [5] ResNet-50-FPN 24.53 19.47 26.04
IDN [16] ResNet50 26.29 22.61 27.39
Ours ResNet-50-FPN 31.33 24.72 33.31         -----> trained with backbone ResNet-50-FPN

**Comment by fredzzhang** [comment]
Hi @WXLL579,

Thanks for taking an interest in our work.

The HOI model is in fact the same. The difference is in the object detector. Therefore, the "fine-tuning" is referring to the object detector. You can follow the instructions to download the object detections provided by the DRG repo to reproduce the numbers.

Fred.
